### ISSUE TITLE
fail to install colour adafruit

### ISSUE THREAD

**Issue by joeydream** [adafruit/Adafruit_AMG88xx#13]
i am follow the instruction from website and youtube:
https://www.youtube.com/watch?v=CWnVHOqTdrE

but when to the comment:
$ sudo pip install colour Adafruit_AMG88xx

the last prompt out is:
Adafruit-PureIO requires Python `>=3.5.0` but the running Python is 2.7.16

then i try to:
$ sudo apt-get install python3.6

and python3.6 is installed successfully, but run again the pip install colour Adafruit_AMG88xx and get the same result.

finally the 

python thermal_cam.py with error:

ImportError: No module named colour

please help

**Comment by caternuson** [comment]
This is the Arduino library. The Python library is here:
https://github.com/adafruit/Adafruit_CircuitPython_AMG88xx
Guide is here:
https://learn.adafruit.com/adafruit-amg8833-8x8-thermal-camera-sensor/python-circuitpython

**Comment by joeydream** [comment]
thanks for your prompt reply.
AS a freshman in linux and pi, i am trying hard but still not work:

1. I copy the whole directory from website by
   $ sudo git clone https://github.conadafruit/Adafruit_CircuitPython_AGM88xx

2. I install the setup by
   $ sudo python setup.py install

3. and then i try to install adfruit...amg88xx
    $ sudo pip3 install adafruit_circuitPython_AMG88xx

they are success, but when i get into examples, the file still can't work

please give me some suggestion:

P.S.: i am using RPi zero w
   $

**Comment by caternuson** [comment]
Closing since this is not an issue with this repo.

Please make sure you are using Python 3 and be sure to follow the guide:
https://learn.adafruit.com/adafruit-amg8833-8x8-thermal-camera-sensor/python-circuitpython#python-installation-of-amg88xx-library-8-6
There is no cloning of the repo involved.

**Comment by joeydream** [comment]
thanks for your reply.
however it still no work after i install the circuitpython successfully

$ sudo pip3 install adafruit-circuitpython-amg88xx

when i try to use the file  "amg88xx_rpi_thermal_cam.py" in circuitpython:
Traceback (most recent call last):
  File "amg88xx_rpi_thermal_cam.py", line 8, in <module>
    import busio
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_Blinka-4.8.0-py2.7.egg/busio.py", line 78
    def readfrom_into(self, address, buffer, *, start=0, end=None):
                                              ^
SyntaxError: invalid syntax

when i try the file "thermal_cam.py" in AMG88xx
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "thermal_cam.py", line 10, in <module>
    from colour import Color
ImportError: No module named colour

**Comment by caternuson** [comment]
>  File "/usr/local/lib/python2.7/dist-packages/Adafruit_Blinka-4.8.0-py2.7.egg/busio.py", line 78

You are using Python 2. Make sure you are using Python 3. Try invoking with `python3` instead of just `python`.

**Comment by joeydream** [comment]
sorry, still not work

pi@raspberrypi:/Adafruit_CircuitPython_AMG88xx/examples $ python3 amg88xx_rpi_thermal_cam.py

pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "amg88xx_rpi_thermal_cam.py", line 13, in <module>
    from scipy.interpolate import griddata
ModuleNotFoundError: No module named 'scipy'

**Comment by caternuson** [comment]
>  ModuleNotFoundError: No module named 'scipy'

Please follow the guide:
https://learn.adafruit.com/adafruit-amg8833-8x8-thermal-camera-sensor/raspberry-pi-thermal-camera#install-python-software-10-7
