### ISSUE TITLE
Why does this library have "depends=Adafruit ST7735 and ST7789 Library, Adafruit ILI9341"?

### ISSUE THREAD

**Issue by IanMercer** [adafruit/Adafruit_AMG88xx#16]
The `library.properties` file includes the line `depends=Adafruit ST7735 and ST7789 Library, Adafruit ILI9341` but there is no reason why an IR Camera Sensor should depend on a TFT display library. I want to use it without that dependency.

**Comment by caternuson** [comment]
Those libraries are needed by some of the examples. If you aren't using one of those TFT displays, then you don't need them.
