### ISSUE TITLE
I'd like to suggest an addition to the AMG88xx library...

### ISSUE THREAD

**Issue by utacc** [adafruit/Adafruit_AMG88xx#4]
I noticed this afternoon that the default Adafruit AMG88xx library has the following behavior: in the Adafruit_AMG88xx::begin() method, although the method returns a boolean, at no point does the method seem to actively query the AMG88xx that's been initialized, to see if it's actually there; nor does the method seem to have any option to return false.
I need that functionality for the project I'm working on, to that end, I'd like to propose the following minor changes both to Adafruit_AMG88xx.h and to Adafruit_AMG88xx.cpp:

to Adafruit_AMG88xx.h: 

@@ -103,10 +103,11 @@ class Adafruit_AMG88xx {
 		//this will manually set hysteresis
 		void	  setInterruptLevels(float high, float low, float hysteresis);
 		
 	private:
 		uint8_t _i2caddr;
+		uint8_t _AMG88xx_status;
 		
 		void      write8(byte reg, byte value);
 		void      write16(byte reg, uint16_t value);
         uint8_t   read8(byte reg);
 		

to Adafruit_AMG88xx.cpp:

@@ -37,11 +37,15 @@ bool Adafruit_AMG88xx::begin(uint8_t addr)
 	_fpsc.FPS = AMG88xx_FPS_10;
 	write8(AMG88xx_FPSC, _fpsc.get());
 
 	delay(100);
 
-	return true;
+	// Read the Status Register (0x04). If it's anything other than 0...bad news bears...sorry... 
+	_AMG88xx_status = read8(0x04);
+	if (_AMG88xx_status == 0) return true;
+
+	return false;
 }
 
 /**************************************************************************/
 /*! 
     @brief  Set the moving average mode.

In the current copy of my own library, I've actually set the return value of the ::begin() function in Adafruit_AMG88xx.cpp to return a uint8_t. This is to maintain interface compatibility with the other imaging sensors I'm working with; I can submit a diff for that, although it might not be for everyone.

Hope someone find this useful.

**Comment by jamesdanielv** [comment]
hello i have made several modifications to one of the example files. 
color index tables are now in progmem (saves 512 byte)
extreme performance boosts. give it a try implement what you want..

code is here https://github.com/jamesdanielv/thermalcam
for example:
const PROGMEM uint16_t camColors[] =  {0x480F,
0x400F,0x400F,0x400F,0x4010,0x3810,0x3810,0x3810,0x3810,0x3010,0x3010,
0x3010,0x2810,0x2810,0x2810,0x2810,0x2010,0x2010,0x2010,0x1810,0x1810,
0x1811,0x1811,0x1011,0x1011,0x1011,0x0811,0x0811,0x0811,0x0011,0x0011,
0x0011,0x0011,0x0011,0x0031,0x0031,0x0051,0x0072,0x0072,0x0092,0x00B2,
0x00B2,0x00D2,0x00F2,0x00F2,0x0112,0x0132,0x0152,0x0152,0x0172,0x0192,
0x0192,0x01B2,0x01D2,0x01F3,0x01F3,0x0213,0x0233,0x0253,0x0253,0x0273,
0x0293,0x02B3,0x02D3,0x02D3,0x02F3,0x0313,0x0333,0x0333,0x0353,0x0373,
0x0394,0x03B4,0x03D4,0x03D4,0x03F4,0x0414,0x0434,0x0454,0x0474,0x0474,
0x0494,0x04B4,0x04D4,0x04F4,0x0514,0x0534,0x0534,0x0554,0x0554,0x0574,
0x0574,0x0573,0x0573,0x0573,0x0572,0x0572,0x0572,0x0571,0x0591,0x0591,
0x0590,0x0590,0x058F,0x058F,0x058F,0x058E,0x05AE,0x05AE,0x05AD,0x05AD,
0x05AD,0x05AC,0x05AC,0x05AB,0x05CB,0x05CB,0x05CA,0x05CA,0x05CA,0x05C9,
0x05C9,0x05C8,0x05E8,0x05E8,0x05E7,0x05E7,0x05E6,0x05E6,0x05E6,0x05E5,
0x05E5,0x0604,0x0604,0x0604,0x0603,0x0603,0x0602,0x0602,0x0601,0x0621,
0x0621,0x0620,0x0620,0x0620,0x0620,0x0E20,0x0E20,0x0E40,0x1640,0x1640,
0x1E40,0x1E40,0x2640,0x2640,0x2E40,0x2E60,0x3660,0x3660,0x3E60,0x3E60,
0x3E60,0x4660,0x4660,0x4E60,0x4E80,0x5680,0x5680,0x5E80,0x5E80,0x6680,
0x6680,0x6E80,0x6EA0,0x76A0,0x76A0,0x7EA0,0x7EA0,0x86A0,0x86A0,0x8EA0,
0x8EC0,0x96C0,0x96C0,0x9EC0,0x9EC0,0xA6C0,0xAEC0,0xAEC0,0xB6E0,0xB6E0,
0xBEE0,0xBEE0,0xC6E0,0xC6E0,0xCEE0,0xCEE0,0xD6E0,0xD700,0xDF00,0xDEE0,
0xDEC0,0xDEA0,0xDE80,0xDE80,0xE660,0xE640,0xE620,0xE600,0xE5E0,0xE5C0,
0xE5A0,0xE580,0xE560,0xE540,0xE520,0xE500,0xE4E0,0xE4C0,0xE4A0,0xE480,
0xE460,0xEC40,0xEC20,0xEC00,0xEBE0,0xEBC0,0xEBA0,0xEB80,0xEB60,0xEB40,
0xEB20,0xEB00,0xEAE0,0xEAC0,0xEAA0,0xEA80,0xEA60,0xEA40,0xF220,0xF200,
0xF1E0,0xF1C0,0xF1A0,0xF180,0xF160,0xF140,0xF100,0xF0E0,0xF0C0,0xF0A0,
0xF080,0xF060,0xF040,0xF020,0xF800,};

and to read it 
pgm_read_word_near(camColors+colorIndex));
[thermal_cam.ino.zip](https://github.com/adafruit/Adafruit_AMG88xx/files/2182497/thermal_cam.ino.zip)

**Comment by caternuson** [comment]
Should be fixed with #22
