### ISSUE TITLE
stat and sclr get() mask values

### ISSUE THREAD

**Issue by rheurtley** [adafruit/Adafruit_AMG88xx#7]
In the Adafruit_AMG88xx.h file, the mask values for the stat and sclr structure get() functions are 0x07. Shouldn't they be 0x0f? The return value is contained in bits 3-1 with bit 0 always zero.

**Comment by deanm1278** [comment]
fixed! https://github.com/adafruit/Adafruit_AMG88xx/commit/3c0bcf8ec7c1f79e1949458af32f5d850f5589dc
